export const juegosList = [
    {
        id: 1,
        nombre: 'Mario Bros',
        img: "./media/img/Mario_Bros._NES_Cover.webp",
        precioentero: 99,
        preciocentavos:99,
        descripcion: 'El clásico juego de Mario Bros lanzado en 1983 remasterizado para PC.',
    },
    {
        id: 2,
        nombre: 'Age of Empires II',
        img: "./media/img/Age_of_Empires_II_HD_Edition.webp",
        precioentero: 47,
        preciocentavos:70,
        descripcion: 'Es un juego de estrategia en tiempo real ambientado en la edad media.',
    },
    {
        id: 3,
        nombre: 'Lineage 2',
        img: "./media/img/lineage-2.webp",
        precioentero: 50,
        preciocentavos:0o0,
        descripcion: 'Es un juego de rol multijugador masivo en línea.',
    },
    {
        id: 4,
        nombre: 'The Elder Scrolls IV: Oblivion',
        img: "./media/img/Copertina_Oblivion.webp",
        precioentero: 70,
        preciocentavos:0o0,
        descripcion: 'La cuarta entrega de la saga The Elder Scrolls nos trae con Oblivion una propuesta muy destacada tanto en jugabilidad como en gráficos.',
    },
    {
        id: 5,
        nombre: 'Cyberpunk 2077',
        img: "./media/img/cyberpunk2077.webp",
        precioentero: 125,
        preciocentavos:55,
        descripcion: 'RPG de acción y aventura de mundo abierto ambientado en el futuro.',
    },
    {
        id: 6,
        nombre: 'Residen Evil 4 - Remake',
        img: "./media/img/resident_evil_4_hd_pc_cover.webp",
        precioentero: 150,
        preciocentavos:30,
        descripcion: 'Remake del clásico Residen Evil 4.',
    }];